version: '3.1'

services:
  proxy:
    image: perconalab/proxysql
    networks:
      - galera
    ports:
      - "3306:3306"
      - "6032:6032"
    env_file: proxysql.env
    deploy:
      mode: replicated
      replicas: 1
      labels: [APP=proxysql]
     # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      # placement constraint - in this case on 'worker' nodes only
      placement:
        constraints: [node.role == manager]

  etcd:
    image: quay.io/coreos/etcd
    command:  etcd
    volumes:
      - /usr/share/ca-certificates/:/etc/ssl/certs
    env_file: etcd.env
    networks:
      - galera
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  percona-xtradb-cluster:
    image: percona/percona-xtradb-cluster:5.7
    networks:
      - galera
    env_file: galera.env
    deploy:
      mode: global
      labels: [APP=pxc]
     # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3
      # placement constraint - in this case on 'worker' nodes only
      placement:
        constraints: [node.role == worker]
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - proxy
    ports:
    - "9191:80"
    environment:
      MYSQL_USER: proxyuser
      MYSQL_PASSWORD: s3cr3TL33tP@ssw0rd
      MYSQL_ROOT_PASSWORD: s3cr3TL33tP@ssw0rd
      MYSQL_PROXY_USER: proxyuser
      MYSQL_PROXY_PASSWORD: s3cr3TL33tPr0xyP@ssw0rd
      PMA_HOST: proxy
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
          
networks:
  galera:
    # Use a custom driver
    driver: overlay
    internal: true
   # ipam:
    #  driver: default
     # config:
      #- subnet: 10.20.1.0/24
