version: "3.2"

services:
  alpine:
    image: alpine
    volumes:
      - type: volume
        source: vol_debug
        target: /foo
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]

volumes:
  vol_debug:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=http://10.64.0.89,rw
      device: ":/mnt/sharedFolder"
