version: "3.2"

services:
  alpine:
    image: alpine
    volumes:
      - type: volume
        source: mysql_vol_debug
        target: /foo
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == worker]
