version: "3.2"

services:
  portainer:
    image: portainer/portainer
    container_name: "portainer-app"
    ports:
      - 9000:9000
      - 8000:8000
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
  visualizer:
    image: dockersamples/visualizer
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    ports:
      - 8080:8080
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
   phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - proxy
    ports:
    - "9191:80"
    environment:
      MYSQL_USER: proxyuser
      MYSQL_PASSWORD: s3cr3TL33tP@ssw0rd
      MYSQL_ROOT_PASSWORD: s3cr3TL33tP@ssw0rd
      MYSQL_PROXY_USER: proxyuser
      MYSQL_PROXY_PASSWORD: s3cr3TL33tPr0xyP@ssw0rd
      PMA_HOST: proxy
    deploy:
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
