version: '2'
 
services:
 proxy:
   image: perconalab/proxysql
   networks:
    - front
    - Theistareykjarbunga
   ports:
    - "3306:3306"
    - "6032:6032"
   env_file: .env
 percona-xtradb-cluster:
   image: percona/percona-xtradb-cluster:5.6
   networks:
    - Theistareykjarbunga
   ports:
    - "3306"
   env_file: .env
networks:
 Theistareykjarbunga:
  driver: overlay
 front:
  driver: overlay
