version: '3'
 
services:
 proxy:
   image: perconalab/proxysql
   networks:
    - front
    - Theistareykjarbunga
   ports:
    - "3306:3306"
    - "6032:6032"
   env_file: .env
 percona-xtradb-cluster:
   image: percona/percona-xtradb-cluster:5.6
   networks:
    - Theistareykjarbunga
   ports:
    - "3306"
   env_file: .env
 phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
    - proxy
    ports:
    - "9191:80"
    environment:
      MYSQL_USER: proxyuser
      MYSQL_PASSWORD: s3cret
      MYSQL_ROOT_PASSWORD: s3cret
      PMA_HOST: proxy
    networks:
    - front
networks:
 Theistareykjarbunga:
  driver: overlay
 front:
  driver: overlay
